dist: trusty
sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8
    
before_script:
  - docker pull guigolab/ipsa-nf@sha256:88e680da318023d2a577893d5c4f0324ad720f83b13830b4e29f2d03f77490bb
  - curl -fsSL get.nextflow.io | bash && mv nextflow $HOME/bin

script:
  - ./ci run --microexons && ./ci validate